// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Package nftables contains the first, deliberately small no-eBPF nftables
// renderer used to prove the linux-route product-demo direction before it is
// wired into the agent. It is intentionally pure string rendering for now: the
// Phase 0 spike needs reviewable desired state and unit tests before adding a
// privileged netlink executor.
package nftables

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"
)

const (
	// TableName is the nftables table owned exclusively by Cilium no-eBPF mode.
	TableName = "cilium_noebpf"
)

// Protocol is the L4 protocol used by Service and policy rules.
type Protocol string

const (
	ProtocolTCP Protocol = "tcp"
	ProtocolUDP Protocol = "udp"
)

// ServiceDNAT is the minimal Phase 0 Service translation tuple. M1 will replace
// this one-rule-per-backend shape with set/map based rendering once the hook
// order and cleanup contract are proven.
type ServiceDNAT struct {
	FrontendAddr netip.Addr
	FrontendPort uint16
	Protocol     Protocol
	BackendAddr  netip.Addr
	BackendPort  uint16
}

// PolicyAllow is a minimal allow tuple for the Phase 0 default-deny smoke.
type PolicyAllow struct {
	Source      netip.Prefix
	Destination netip.Addr
	Port        uint16
	Protocol    Protocol
}

// EndpointPolicy describes the tiny subset needed for the Phase 0 policy spike.
type EndpointPolicy struct {
	EndpointIP   netip.Addr
	IngressDeny  bool
	EgressDeny   bool
	IngressAllow []PolicyAllow
	EgressAllow  []PolicyAllow
}

// DesiredState is the complete nftables desired-state script input for the
// current spike. It renders a full table replacement scoped to TableName.
type DesiredState struct {
	Services []ServiceDNAT
	Policies []EndpointPolicy
}

// Render returns an nft(8) script that owns only the inet cilium_noebpf table.
// The Phase 0 renderer emits a create-table script because kind currently ships
// nft v1.0.6, where newer destroy-table syntax is unavailable. A future
// privileged executor should handle full replacement by deleting/flushing the
// owned table before applying this desired state.
func Render(state DesiredState) (string, error) {
	for _, svc := range state.Services {
		if err := svc.validate(); err != nil {
			return "", err
		}
	}
	for _, pol := range state.Policies {
		if err := pol.validate(); err != nil {
			return "", err
		}
	}

	var b strings.Builder
	b.WriteString("# generated by Cilium no-eBPF nftables renderer\n")
	b.WriteString("table inet " + TableName + " {\n")
	b.WriteString("\tchain service_prerouting {\n")
	b.WriteString("\t\ttype nat hook prerouting priority dstnat; policy accept;\n")
	for _, svc := range sortedServices(state.Services) {
		b.WriteString("\t\t" + svc.dnatRule() + "\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("\tchain service_output {\n")
	b.WriteString("\t\ttype nat hook output priority -100; policy accept;\n")
	for _, svc := range sortedServices(state.Services) {
		b.WriteString("\t\t" + svc.dnatRule() + "\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("\tchain policy_forward {\n")
	b.WriteString("\t\ttype filter hook forward priority filter; policy accept;\n")
	b.WriteString("\t\tct state established,related accept\n")
	for _, pol := range sortedPolicies(state.Policies) {
		for _, allow := range sortedAllows(pol.IngressAllow) {
			b.WriteString("\t\t" + allow.ingressRule() + "\n")
		}
		for _, allow := range sortedAllows(pol.EgressAllow) {
			b.WriteString("\t\t" + allow.egressRule() + "\n")
		}
		if pol.IngressDeny {
			b.WriteString("\t\t" + addrFamily(pol.EndpointIP) + " daddr " + pol.EndpointIP.String() + " drop\n")
		}
		if pol.EgressDeny {
			b.WriteString("\t\t" + addrFamily(pol.EndpointIP) + " saddr " + pol.EndpointIP.String() + " drop\n")
		}
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func (s ServiceDNAT) validate() error {
	if !s.FrontendAddr.IsValid() || !s.BackendAddr.IsValid() {
		return fmt.Errorf("service DNAT requires valid frontend and backend addresses")
	}
	if s.FrontendAddr.Is4() != s.BackendAddr.Is4() {
		return fmt.Errorf("service DNAT does not support NAT46/NAT64 in no-eBPF M1")
	}
	if s.FrontendPort == 0 || s.BackendPort == 0 {
		return fmt.Errorf("service DNAT requires non-zero ports")
	}
	return validateProtocol(s.Protocol)
}

func (p EndpointPolicy) validate() error {
	if !p.EndpointIP.IsValid() {
		return fmt.Errorf("endpoint policy requires a valid endpoint IP")
	}
	for _, allow := range append(append([]PolicyAllow{}, p.IngressAllow...), p.EgressAllow...) {
		if !allow.Source.IsValid() || !allow.Destination.IsValid() {
			return fmt.Errorf("policy allow requires valid source prefix and destination IP")
		}
		if allow.Source.Addr().Is4() != allow.Destination.Is4() {
			return fmt.Errorf("policy allow source and destination IP families must match")
		}
		if allow.Port == 0 {
			return fmt.Errorf("policy allow requires a non-zero port")
		}
		if err := validateProtocol(allow.Protocol); err != nil {
			return err
		}
	}
	return nil
}

func validateProtocol(proto Protocol) error {
	switch proto {
	case ProtocolTCP, ProtocolUDP:
		return nil
	default:
		return fmt.Errorf("unsupported no-eBPF M1 protocol %q", proto)
	}
}

func (s ServiceDNAT) dnatRule() string {
	family := addrFamily(s.FrontendAddr)
	backend := s.BackendAddr.String()
	if s.BackendAddr.Is6() {
		backend = "[" + backend + "]"
	}
	return fmt.Sprintf("%s daddr %s %s dport %d dnat to %s:%d",
		family, s.FrontendAddr, s.Protocol, s.FrontendPort, backend, s.BackendPort)
}

func (a PolicyAllow) ingressRule() string {
	family := prefixFamily(a.Source)
	return fmt.Sprintf("%s saddr %s %s daddr %s %s dport %d accept",
		family, a.Source, family, a.Destination, a.Protocol, a.Port)
}

func (a PolicyAllow) egressRule() string {
	family := prefixFamily(a.Source)
	return fmt.Sprintf("%s saddr %s %s daddr %s %s dport %d accept",
		family, a.Source, family, a.Destination, a.Protocol, a.Port)
}

func addrFamily(addr netip.Addr) string {
	if addr.Is4() {
		return "ip"
	}
	return "ip6"
}

func prefixFamily(prefix netip.Prefix) string {
	if prefix.Addr().Is4() {
		return "ip"
	}
	return "ip6"
}

func sortedServices(in []ServiceDNAT) []ServiceDNAT {
	out := append([]ServiceDNAT(nil), in...)
	sort.Slice(out, func(i, j int) bool { return out[i].dnatRule() < out[j].dnatRule() })
	return out
}

func sortedPolicies(in []EndpointPolicy) []EndpointPolicy {
	out := append([]EndpointPolicy(nil), in...)
	sort.Slice(out, func(i, j int) bool { return out[i].EndpointIP.Less(out[j].EndpointIP) })
	return out
}

func sortedAllows(in []PolicyAllow) []PolicyAllow {
	out := append([]PolicyAllow(nil), in...)
	sort.Slice(out, func(i, j int) bool {
		return out[i].Source.String()+out[i].Destination.String() < out[j].Source.String()+out[j].Destination.String()
	})
	return out
}
