// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Package nftables contains the no-eBPF nftables renderer used by the
// linux-route branch. It renders reviewable desired state for the owned
// cilium_noebpf table and is backed by unit tests before the privileged netlink
// executor applies it.
package nftables

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"
)

const (
	// TableName is the nftables table owned exclusively by Cilium no-eBPF mode.
	TableName = "cilium_noebpf"
)

// Protocol is the L4 protocol used by Service and policy rules.
type Protocol string

const (
	ProtocolTCP  Protocol = "tcp"
	ProtocolUDP  Protocol = "udp"
	ProtocolSCTP Protocol = "sctp"
)

// ServiceDNAT is the Service translation tuple rendered into the owned nftables
// table. The renderer currently emits one rule per backend to keep the
// generated state easy to review and reconcile.
type ServiceDNAT struct {
	FrontendAddr    netip.Addr
	FrontendPort    uint16
	Protocol        Protocol
	BackendAddr     netip.Addr
	BackendPort     uint16
	NodePort        bool
	SourceRanges    []netip.Prefix
	SessionAffinity bool
}

// PolicyAllow is a minimal allow tuple for the Phase 0 default-deny smoke.
type PolicyAllow struct {
	Source      netip.Prefix
	Destination netip.Prefix
	Port        uint16
	EndPort     uint16
	Protocol    Protocol
}

// EndpointPolicy describes the tiny subset needed for the Phase 0 policy spike.
type EndpointPolicy struct {
	EndpointIP       netip.Addr
	IngressDeny      bool
	EgressDeny       bool
	IngressAllow     []PolicyAllow
	EgressAllow      []PolicyAllow
	IngressDenyRules []PolicyDeny
	EgressDenyRules  []PolicyDeny
}

// DesiredState is the complete nftables desired-state script input for the
// current spike. It renders a full table replacement scoped to TableName.
type DesiredState struct {
	Services []ServiceDNAT
	Policies []EndpointPolicy
}

// Render returns an nft(8) script that owns only the inet cilium_noebpf table.
// The Phase 0 renderer emits a create-table script because kind currently ships
// nft v1.0.6, where newer destroy-table syntax is unavailable. A future
// privileged executor should handle full replacement by deleting/flushing the
// owned table before applying this desired state.
func Render(state DesiredState) (string, error) {
	for _, svc := range state.Services {
		if err := svc.validate(); err != nil {
			return "", err
		}
	}
	for _, pol := range state.Policies {
		if err := pol.validate(); err != nil {
			return "", err
		}
	}

	var b strings.Builder
	b.WriteString("# generated by Cilium no-eBPF nftables renderer\n")
	b.WriteString("table inet " + TableName + " {\n")
	b.WriteString("\tchain service_prerouting {\n")
	b.WriteString("\t\ttype nat hook prerouting priority dstnat; policy accept;\n")
	for _, svc := range groupedServices(state.Services) {
		for _, rule := range svc.dnatRules() {
			b.WriteString("\t\t" + rule + "\n")
		}
	}
	b.WriteString("\t}\n")
	b.WriteString("\tchain service_output {\n")
	b.WriteString("\t\ttype nat hook output priority -100; policy accept;\n")
	for _, svc := range groupedServices(state.Services) {
		for _, rule := range svc.dnatRules() {
			b.WriteString("\t\t" + rule + "\n")
		}
	}
	b.WriteString("\t}\n")
	b.WriteString("\tchain policy_forward {\n")
	b.WriteString("\t\ttype filter hook forward priority filter; policy accept;\n")
	b.WriteString("\t\tct state established,related accept\n")
	for _, pol := range groupedEndpointPolicies(state.Policies) {
		for _, deny := range sortedDenies(pol.IngressDenyRules) {
			b.WriteString("\t\t" + deny.ingressRule() + "\n")
		}
		for _, deny := range sortedDenies(pol.EgressDenyRules) {
			b.WriteString("\t\t" + deny.egressRule() + "\n")
		}
		for _, allow := range sortedAllows(pol.IngressAllow) {
			b.WriteString("\t\t" + allow.ingressRule() + "\n")
		}
		for _, allow := range sortedAllows(pol.EgressAllow) {
			b.WriteString("\t\t" + allow.egressRule() + "\n")
		}
		if pol.IngressDeny {
			b.WriteString("\t\t" + addrFamily(pol.EndpointIP) + " daddr " + pol.EndpointIP.String() + " counter drop\n")
		}
		if pol.EgressDeny {
			b.WriteString("\t\t" + addrFamily(pol.EndpointIP) + " saddr " + pol.EndpointIP.String() + " counter drop\n")
		}
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func (s ServiceDNAT) validate() error {
	if !s.FrontendAddr.IsValid() || !s.BackendAddr.IsValid() {
		return fmt.Errorf("service DNAT requires valid frontend and backend addresses")
	}
	if s.FrontendAddr.Is4() != s.BackendAddr.Is4() {
		return fmt.Errorf("service DNAT does not support NAT46/NAT64 in no-eBPF mode")
	}
	if s.FrontendPort == 0 || s.BackendPort == 0 {
		return fmt.Errorf("service DNAT requires non-zero ports")
	}
	for _, prefix := range s.SourceRanges {
		if !prefix.IsValid() {
			return fmt.Errorf("service DNAT requires valid source ranges")
		}
	}
	return validateProtocol(s.Protocol)
}

func (p EndpointPolicy) validate() error {
	if !p.EndpointIP.IsValid() {
		return fmt.Errorf("endpoint policy requires a valid endpoint IP")
	}
	for _, allow := range append(append([]PolicyAllow{}, p.IngressAllow...), p.EgressAllow...) {
		if err := validateRuleTuple(allow.Source, allow.Destination, allow.Port, allow.EndPort, allow.Protocol); err != nil {
			return err
		}
	}
	for _, deny := range append(append([]PolicyDeny{}, p.IngressDenyRules...), p.EgressDenyRules...) {
		if err := validateRuleTuple(deny.Source, deny.Destination, deny.Port, deny.EndPort, deny.Protocol); err != nil {
			return err
		}
	}
	return nil
}

func validateRuleTuple(source, destination netip.Prefix, port, endPort uint16, proto Protocol) error {
	if !source.IsValid() || !destination.IsValid() {
		return fmt.Errorf("policy rule requires valid source and destination prefixes")
	}
	if source.Addr().Is4() != destination.Addr().Is4() {
		return fmt.Errorf("policy rule source and destination families must match")
	}
	if port == 0 && endPort != 0 {
		return fmt.Errorf("policy rule endPort requires a starting port")
	}
	if endPort != 0 && endPort < port {
		return fmt.Errorf("policy rule endPort must be >= port")
	}
	if err := validateProtocol(proto); err != nil {
		return err
	}
	return nil
}

func validateProtocol(proto Protocol) error {
	switch proto {
	case ProtocolTCP, ProtocolUDP, ProtocolSCTP:
		return nil
	default:
		return fmt.Errorf("unsupported no-eBPF protocol %q", proto)
	}
}

type serviceKey struct {
	addr     netip.Addr
	port     uint16
	protocol Protocol
	nodePort bool
	affinity bool
}

type serviceGroup struct {
	serviceKey
	sourceRanges []netip.Prefix
	backends     []serviceBackend
}

type serviceBackend struct {
	addr netip.Addr
	port uint16
}

func (s ServiceDNAT) serviceKey() serviceKey {
	return serviceKey{
		addr:     s.FrontendAddr,
		port:     s.FrontendPort,
		protocol: s.Protocol,
		nodePort: s.NodePort,
		affinity: s.SessionAffinity,
	}
}

func (s serviceGroup) dnatRules() []string {
	rules := make([]string, 0, len(s.backends))
	sourceMatches := s.sourceRangeMatches()
	if len(s.sourceRanges) > 0 && len(sourceMatches) == 0 {
		return nil
	}
	for i, backend := range s.backends {
		match := s.match()
		if len(sourceMatches) == 0 {
			rule := match
			if i < len(s.backends)-1 {
				rule += backendSelectionExpression(s.serviceKey, len(s.backends), i)
			}
			rule += " counter dnat to " + formatBackend(backend.addr, backend.port)
			rules = append(rules, rule)
			continue
		}
		for _, sourceMatch := range sourceMatches {
			rule := sourceMatch + " " + match
			if i < len(s.backends)-1 {
				rule += backendSelectionExpression(s.serviceKey, len(s.backends), i)
			}
			rule += " counter dnat to " + formatBackend(backend.addr, backend.port)
			rules = append(rules, rule)
		}
	}
	return rules
}

func backendSelectionExpression(key serviceKey, total, index int) string {
	if key.affinity {
		return fmt.Sprintf(" jhash %s saddr mod %d == %d", backendHashFamily(key.addr), total, index)
	}
	return fmt.Sprintf(" numgen random mod %d == %d", total, index)
}

func backendHashFamily(addr netip.Addr) string {
	if addr.Is4() {
		return "ip"
	}
	return "ip6"
}

func (s serviceGroup) sourceRangeMatches() []string {
	if len(s.sourceRanges) == 0 {
		return nil
	}
	var out []string
	for _, prefix := range s.sourceRanges {
		if prefix.Addr().Is4() != s.addr.Is4() {
			continue
		}
		out = append(out, sourcePrefixMatch(prefix))
	}
	return out
}

func (s serviceGroup) match() string {
	family := addrFamily(s.addr)
	if s.nodePort && s.addr.IsUnspecified() {
		nfproto := "ipv6"
		if s.addr.Is4() {
			nfproto = "ipv4"
		}
		return fmt.Sprintf("meta nfproto %s %s dport %d", nfproto, s.protocol, s.port)
	}
	return fmt.Sprintf("%s daddr %s %s dport %d", family, s.addr, s.protocol, s.port)
}

func formatBackend(addr netip.Addr, port uint16) string {
	backend := addr.String()
	if addr.Is6() {
		backend = "[" + backend + "]"
	}
	return fmt.Sprintf("%s:%d", backend, port)
}

func (a PolicyAllow) ingressRule() string {
	return a.rule()
}

func (a PolicyAllow) egressRule() string {
	return a.rule()
}

func (a PolicyAllow) rule() string {
	return policyRuleString(a.Source, a.Destination, a.Port, a.EndPort, a.Protocol, "accept")
}

func (a PolicyDeny) ingressRule() string {
	return a.rule()
}

func (a PolicyDeny) egressRule() string {
	return a.rule()
}

func (a PolicyDeny) rule() string {
	return policyRuleString(a.Source, a.Destination, a.Port, a.EndPort, a.Protocol, "drop")
}

func policyRuleString(source, destination netip.Prefix, port, endPort uint16, proto Protocol, verdict string) string {
	family := prefixFamily(source)
	if port == 0 && endPort == 0 {
		return fmt.Sprintf("%s saddr %s %s daddr %s counter %s",
			family, source, family, destination, verdict)
	}
	portExpr := fmt.Sprintf("%d", port)
	if endPort != 0 && endPort != port {
		portExpr = fmt.Sprintf("%d-%d", port, endPort)
	}
	return fmt.Sprintf("%s saddr %s %s daddr %s %s dport %s counter %s",
		family, source, family, destination, proto, portExpr, verdict)
}

func addrFamily(addr netip.Addr) string {
	if addr.Is4() {
		return "ip"
	}
	return "ip6"
}

func prefixFamily(prefix netip.Prefix) string {
	if prefix.Addr().Is4() {
		return "ip"
	}
	return "ip6"
}

func groupedServices(in []ServiceDNAT) []serviceGroup {
	type groupedService struct {
		backends     []serviceBackend
		sourceRanges []netip.Prefix
	}
	byKey := map[serviceKey]*groupedService{}
	for _, svc := range in {
		key := svc.serviceKey()
		group := byKey[key]
		if group == nil {
			group = &groupedService{}
			byKey[key] = group
		}
		group.backends = append(group.backends, serviceBackend{addr: svc.BackendAddr, port: svc.BackendPort})
		group.sourceRanges = appendUniquePrefixes(group.sourceRanges, svc.SourceRanges)
	}
	out := make([]serviceGroup, 0, len(byKey))
	for key, group := range byKey {
		backends := group.backends
		sort.Slice(backends, func(i, j int) bool {
			if backends[i].addr == backends[j].addr {
				return backends[i].port < backends[j].port
			}
			return backends[i].addr.Less(backends[j].addr)
		})
		sourceRanges := append([]netip.Prefix(nil), group.sourceRanges...)
		sort.Slice(sourceRanges, func(i, j int) bool {
			if sourceRanges[i].Addr() == sourceRanges[j].Addr() {
				return sourceRanges[i].Bits() < sourceRanges[j].Bits()
			}
			return sourceRanges[i].Addr().Less(sourceRanges[j].Addr())
		})
		out = append(out, serviceGroup{serviceKey: key, sourceRanges: sourceRanges, backends: backends})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].addr == out[j].addr {
			if out[i].port == out[j].port {
				if out[i].protocol == out[j].protocol {
					if out[i].nodePort == out[j].nodePort {
						return !out[i].affinity && out[j].affinity
					}
					return !out[i].nodePort && out[j].nodePort
				}
				return out[i].protocol < out[j].protocol
			}
			return out[i].port < out[j].port
		}
		return out[i].addr.Less(out[j].addr)
	})
	return out
}

func appendUniquePrefixes(dst, in []netip.Prefix) []netip.Prefix {
	for _, prefix := range in {
		found := false
		for _, existing := range dst {
			if existing == prefix {
				found = true
				break
			}
		}
		if !found {
			dst = append(dst, prefix)
		}
	}
	return dst
}

func sourcePrefixMatch(prefix netip.Prefix) string {
	family := "ip"
	if prefix.Addr().Is6() {
		family = "ip6"
	}
	return fmt.Sprintf("%s saddr %s", family, prefix)
}

type endpointPolicyGroup struct {
	EndpointIP       netip.Addr
	IngressDeny      bool
	EgressDeny       bool
	IngressAllow     []PolicyAllow
	EgressAllow      []PolicyAllow
	IngressDenyRules []PolicyDeny
	EgressDenyRules  []PolicyDeny
}

func groupedEndpointPolicies(in []EndpointPolicy) []endpointPolicyGroup {
	byIP := map[netip.Addr]*endpointPolicyGroup{}
	for _, pol := range in {
		group := byIP[pol.EndpointIP]
		if group == nil {
			group = &endpointPolicyGroup{EndpointIP: pol.EndpointIP}
			byIP[pol.EndpointIP] = group
		}
		group.IngressDeny = group.IngressDeny || pol.IngressDeny
		group.EgressDeny = group.EgressDeny || pol.EgressDeny
		group.IngressAllow = append(group.IngressAllow, pol.IngressAllow...)
		group.EgressAllow = append(group.EgressAllow, pol.EgressAllow...)
		group.IngressDenyRules = append(group.IngressDenyRules, pol.IngressDenyRules...)
		group.EgressDenyRules = append(group.EgressDenyRules, pol.EgressDenyRules...)
	}
	out := make([]endpointPolicyGroup, 0, len(byIP))
	for _, group := range byIP {
		out = append(out, *group)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].EndpointIP.Less(out[j].EndpointIP) })
	return out
}

func sortedAllows(in []PolicyAllow) []PolicyAllow {
	out := append([]PolicyAllow(nil), in...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].Source.String() != out[j].Source.String() {
			return out[i].Source.String() < out[j].Source.String()
		}
		if out[i].Destination.String() != out[j].Destination.String() {
			return out[i].Destination.String() < out[j].Destination.String()
		}
		if out[i].Protocol != out[j].Protocol {
			return out[i].Protocol < out[j].Protocol
		}
		if out[i].Port != out[j].Port {
			return out[i].Port < out[j].Port
		}
		return out[i].EndPort < out[j].EndPort
	})
	return out
}

func sortedDenies(in []PolicyDeny) []PolicyDeny {
	out := append([]PolicyDeny(nil), in...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].Source.String() != out[j].Source.String() {
			return out[i].Source.String() < out[j].Source.String()
		}
		if out[i].Destination.String() != out[j].Destination.String() {
			return out[i].Destination.String() < out[j].Destination.String()
		}
		if out[i].Protocol != out[j].Protocol {
			return out[i].Protocol < out[j].Protocol
		}
		if out[i].Port != out[j].Port {
			return out[i].Port < out[j].Port
		}
		return out[i].EndPort < out[j].EndPort
	})
	return out
}
