// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NoEBPFStatus describes the current no-eBPF support surface exposed through
// the agent status API.
//
// +k8s:deepcopy-gen=true
//
// swagger:model NoEBPFStatus
type NoEBPFStatus struct {
	Enabled              bool               `json:"enabled,omitempty"`
	ServicesEnabled      bool               `json:"services-enabled,omitempty"`
	NetworkPolicyEnabled bool               `json:"network-policy-enabled,omitempty"`
	Capabilities         []NoEBPFCapability `json:"capabilities,omitempty"`
}

// NoEBPFCapability captures one capability entry in the no-eBPF support matrix.
//
// +k8s:deepcopy-gen=true
//
// swagger:model NoEBPFCapability
type NoEBPFCapability struct {
	Name  string `json:"name,omitempty"`
	Level string `json:"level,omitempty"`
	Notes string `json:"notes,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *NoEBPFStatus) DeepCopyInto(out *NoEBPFStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]NoEBPFCapability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a new deep-copied value.
func (in *NoEBPFStatus) DeepCopy() *NoEBPFStatus {
	if in == nil {
		return nil
	}
	out := new(NoEBPFStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NoEBPFCapability) DeepCopyInto(out *NoEBPFCapability) {
	*out = *in
}

// DeepCopy creates a new deep-copied value.
func (in *NoEBPFCapability) DeepCopy() *NoEBPFCapability {
	if in == nil {
		return nil
	}
	out := new(NoEBPFCapability)
	in.DeepCopyInto(out)
	return out
}

// Validate validates this no eBPF status.
func (m *NoEBPFStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this no eBPF status based on context it is used.
func (m *NoEBPFStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation.
func (m *NoEBPFStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *NoEBPFStatus) UnmarshalBinary(b []byte) error {
	var res NoEBPFStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// Validate validates this no eBPF capability.
func (m *NoEBPFCapability) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this no eBPF capability based on context it is used.
func (m *NoEBPFCapability) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation.
func (m *NoEBPFCapability) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *NoEBPFCapability) UnmarshalBinary(b []byte) error {
	var res NoEBPFCapability
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
