apiVersion: v1
kind: Pod
metadata:
  name: netshoot-multi-homed-1
  labels:
    io.cilium.network-interface.attach/eth1: net0
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]
  nodeSelector:
    kubernetes.io/hostname: kind-worker
---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot-multi-homed-2
  labels:
    io.cilium.network-interface.attach/eth1: net0
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]
  nodeSelector:
    kubernetes.io/hostname: kind-worker
---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot-multi-homed-cp
  labels:
    io.cilium.network-interface.attach/eth1: net0
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]
  nodeSelector:
    kubernetes.io/hostname: kind-control-plane
